name: 'Windows Coverage Checks'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and test (defaults to the branch the workflow runs from)'
        required: false
        type: string
        default: ''
      test-jdk-tier1:
        description: 'jdk/tier1'
        type: boolean
        default: false
      test-jdk-tier2:
        description: 'jdk/tier2'
        type: boolean
        default: false
      test-jdk-tier3:
        description: 'jdk/tier3'
        type: boolean
        default: false
      test-jdk-tier4:
        description: 'jdk/tier4'
        type: boolean
        default: false
      test-langtools-tier1:
        description: 'langtools/tier1'
        type: boolean
        default: false
      test-langtools-tier2:
        description: 'langtools/tier2'
        type: boolean
        default: false
      test-langtools-tier3:
        description: 'langtools/tier3'
        type: boolean
        default: false
      test-langtools-tier4:
        description: 'langtools/tier4'
        type: boolean
        default: false
      test-hotspot-tier1:
        description: 'hotspot/tier1'
        type: boolean
        default: true
      test-hotspot-tier2:
        description: 'hotspot/tier2'
        type: boolean
        default: true
      test-hotspot-tier3:
        description: 'hotspot/tier3'
        type: boolean
        default: true
      test-hotspot-tier4:
        description: 'hotspot/tier4'
        type: boolean
        default: false
      test-lib-test-tier1:
        description: 'lib-test/tier1'
        type: boolean
        default: false
      windows-aarch64:
        description: 'Windows 11 on AArch64'
        type: boolean
        default: true
      windows-x64:
        description: 'Windows Server 2022 on x64'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  prepare:
    name: 'Prepare the run'
    runs-on: ubuntu-24.04
    outputs:
      test-groups: ${{ steps.test-groups.outputs.value }}

    steps:
      - name: 'Checkout the scripts'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch }}
          sparse-checkout: |
            .github
            make/conf/github-actions.conf

      - name: 'Build JTReg'
        id: jtreg
        uses: ./.github/actions/build-jtreg

      - name: 'Build test groups list'
        id: test-groups
        run: |
          groups=''
          add() { if [[ "$1" != "false" ]]; then groups+="$2,"; fi; }
          add "${{ github.event.inputs.test-jdk-tier1 }}" "jdk/tier1"
          add "${{ github.event.inputs.test-jdk-tier2 }}" "jdk/tier2"
          add "${{ github.event.inputs.test-jdk-tier3 }}" "jdk/tier3"
          add "${{ github.event.inputs.test-jdk-tier4 }}" "jdk/tier4"
          add "${{ github.event.inputs.test-langtools-tier1 }}" "langtools/tier1"
          add "${{ github.event.inputs.test-langtools-tier2 }}" "langtools/tier2"
          add "${{ github.event.inputs.test-langtools-tier3 }}" "langtools/tier3"
          add "${{ github.event.inputs.test-langtools-tier4 }}" "langtools/tier4"
          add "${{ github.event.inputs.test-hotspot-tier1 }}" "hotspot/tier1"
          add "${{ github.event.inputs.test-hotspot-tier2 }}" "hotspot/tier2"
          add "${{ github.event.inputs.test-hotspot-tier3 }}" "hotspot/tier3"
          add "${{ github.event.inputs.test-hotspot-tier4 }}" "hotspot/tier4"
          add "${{ github.event.inputs.test-lib-test-tier1 }}" "lib-test/tier1"
          groups="${groups%,}"
          echo "value=$groups" >> $GITHUB_OUTPUT

  build-windows-x64:
    name: windows-x64
    needs: prepare
    uses: ./.github/workflows/build-windows.yml
    with:
      platform: windows-x64
      runs-on: windows-2022
      architecture: 'x86.x64'
      msvc-toolset-version: '14.44'
      ref: ${{ github.event.inputs.branch }}
    if: ${{ inputs['windows-x64'] }}

  build-windows-aarch64:
    name: windows-aarch64
    needs: prepare
    uses: ./.github/workflows/build-windows.yml
    with:
      platform: windows-aarch64
      runs-on: windows-11-arm
      architecture: 'ARM64'
      msvc-toolset-version: '14.44'
      ref: ${{ github.event.inputs.branch }}
    if: ${{ inputs['windows-aarch64'] }}

  test-windows-x64:
    name: windows-x64
    needs:
      - prepare
      - build-windows-x64
    uses: ./.github/workflows/test.yml
    with:
      platform: windows-x64
      bootjdk-platform: windows-x64
      architecture: 'x86.x64'
      runs-on: windows-2022
      debug-suffix: -debug
      test-groups: ${{ needs.prepare.outputs.test-groups }}
      ref: ${{ github.event.inputs.branch }}
    if: ${{ inputs['windows-x64'] }}

  test-windows-aarch64:
    name: windows-aarch64
    needs:
      - prepare
      - build-windows-aarch64
    uses: ./.github/workflows/test.yml
    with:
      platform: windows-aarch64
      bootjdk-platform: windows-aarch64
      runs-on: windows-11-arm
      architecture: 'ARM64'
      debug-suffix: -debug
      test-groups: ${{ needs.prepare.outputs.test-groups }}
      ref: ${{ github.event.inputs.branch }}
    if: ${{ inputs['windows-aarch64'] }}
